### PR TITLE
Show leading 0 for one-digit minutes and seconds

### PR DESCRIPTION
**Pull request by Tenzer**
Just a minor correction which gives nicer output, in my opinion.

### CODE REVIEW

**Comment by Tenzer** [comment]
4 years down the line I don't assume this PR will get merged...

**Comment by prologic** [comment]
Oh WoW! I'm so sorry :D

This PR really should have gone upstream :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by Tenzer** [comment]
Looking through the history I can see that my PR was around the time you made a PR to the upstream project to add ETAs to the output, so I might have used your fork directly back then, hence the PR on to here.

As the upstream project already has the proper output this PR has been obsolete for years, it turns out :)

**Comment by prologic** [comment]
I see I see :D All is well that ends well1 Thanks for cleaning this up!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Pull request closed without merging**
